### PR TITLE
Fixed input generation for CakePHP 2.4

### PR DESCRIPTION
**Pull request by mvdriel**
Fixed input generation for CakePHP 2.4; third parameter of HtmlHelper->tag() should be an array. In previous versions a string was processed as an array with one entry "class".

### CODE REVIEW

**Comment by ravage84** [comment]
Just came accross similiar issue. I had an uneditable-input, which broke my app after updating to CakePHP 2.4.
I solved it by this:

```
--- app/Plugin/TwitterBootstrap/View/Helper/BootstrapFormHelper.php (revision 321)
+++ app/Plugin/TwitterBootstrap/View/Helper/BootstrapFormHelper.php (revision 322)
@@ -35,7 +35,7 @@
            }
            return $options;
        } else {
-           return $this->Html->tag('span', $options['value'], $options['class']);
+           return $this->Html->tag('span', $options['value'], $options);
        }
    }
```

**Comment by mvdriel** [comment]
@ravage84 Nice! May I commit your patch to this pull request?

**Comment by mvdriel** [comment]
Until the plugin is patched you can work around this issue by overriding the BootstrapHtmlHelper. Something like this:

``` php
<?php
App::uses('BootstrapHtmlHelper', 'TwitterBootstrap.View/Helper');
class CustomBootstrapHtmlHelper extends BootstrapHtmlHelper {

    public function tag($name, $text = null, $options = array()) {
        if (is_string($options)) {
            $options = array('class' => $options);
        }
        return parent::tag($name, $text, $options);
    }
}
```

**Comment by ravage84** [comment]
@mvdriel Sure you can.

**Comment by mvdriel** [comment]
Added patch from @ravage84

**Comment by slywalker** [comment]
OK, I was merge. Thank you.

**Pull request merged**
